/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import flashcards.Data;
import flashcards.User;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author Victhor
 */
public class TelaUser extends javax.swing.JFrame {
    DefaultListModel modUser = new DefaultListModel();
    ArrayList<User> users;
    /**
     * Creates new form TelaUser
     */
    public TelaUser() {
        users = new ArrayList();
        
        initComponents();
        
        // Hablilitar e desabilitar botões lista de usuários
        
        btnEntrarUser.setEnabled(false);
        btnModificarUser.setEnabled(false);
        btnExcluirUser.setEnabled(false);
        
        lstUsers.setFixedCellHeight(30);
        lstUsers.addListSelectionListener((ListSelectionEvent e) -> {
            if (lstUsers.getSelectedValue() != null) {
                btnEntrarUser.setEnabled(true);
                btnModificarUser.setEnabled(true);
                btnExcluirUser.setEnabled(true);
            } else {
                btnEntrarUser.setEnabled(false);
                btnModificarUser.setEnabled(false);
                btnExcluirUser.setEnabled(false);
            }
        });
        
        // Carregar usuários adicionados anteriormente:
        int iterator = 0;
        boolean verificador;
        
        do {
            User user = new User();
            verificador = user.carregarUser(iterator, user);
            if (verificador)
                users.add(user);
            ++iterator;
        } while(verificador);
        
        lstUsers.setModel(modUser);
        for(int i = 0; i < users.size(); ++i) {
            modUser.addElement(users.get(i).getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotoes = new javax.swing.JPanel();
        btnEntrarUser = new javax.swing.JButton();
        btnModificarUser = new javax.swing.JButton();
        btnExcluirUser = new javax.swing.JButton();
        btnAdicionarUser = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelUser = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstUsers = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Users");
        setBackground(new java.awt.Color(245, 245, 245));
        setResizable(false);

        panelBotoes.setBackground(new java.awt.Color(255, 255, 255));
        panelBotoes.setName(""); // NOI18N

        btnEntrarUser.setText("Entrar");
        btnEntrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarUserActionPerformed(evt);
            }
        });

        btnModificarUser.setText("Modificar");
        btnModificarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUserActionPerformed(evt);
            }
        });

        btnExcluirUser.setText("Excluir");
        btnExcluirUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUserActionPerformed(evt);
            }
        });

        btnAdicionarUser.setText("Adicionar");
        btnAdicionarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnAdicionarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEntrarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntrarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        panelUser.setBackground(new java.awt.Color(245, 245, 245));
        panelUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfis de usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        panelUser.setName(""); // NOI18N

        lstUsers.setToolTipText("");
        jScrollPane2.setViewportView(lstUsers);

        javax.swing.GroupLayout panelUserLayout = new javax.swing.GroupLayout(panelUser);
        panelUser.setLayout(panelUserLayout);
        panelUserLayout.setHorizontalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panelUserLayout.setVerticalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(panelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 112, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 386, Short.MAX_VALUE)
                    .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarUserActionPerformed

        lstUsers.setModel(modUser);
        javax.swing.JTextField tfNome = new javax.swing.JTextField();
        javax.swing.JPasswordField tfSenha = new javax.swing.JPasswordField();

        Object[] message = {
            "Nome: ", tfNome,
            "Senha: ", tfSenha,
        };
        tfSenha.setEchoChar('\u2022');

        int option = JOptionPane.showConfirmDialog(null, message,
                "Adicionar perfil de usuário", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if(option == JOptionPane.OK_OPTION) {
            String nome = tfNome.getText();
            String senha = tfSenha.getText();

            if (nome.equals("") || senha.equals("")) {
                JOptionPane.showMessageDialog(null, "Um ou mais campos não preenchidos.\nO perfil não foi adicionado!",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            } else {
                Calendar c = Calendar.getInstance();
                Data dataDeCriacao = new Data(c.get(Calendar.DAY_OF_MONTH), c.get(Calendar.MONTH), c.get(Calendar.YEAR), c.get(Calendar.HOUR_OF_DAY));
                User newUser = new User(nome, senha, dataDeCriacao);

                users.add(newUser);
                
                // Salvamento automático do usuário:
                newUser.salvarUser();
                
                modUser.addElement(nome); // Só o nome vai aparecer na lista.
            }
        }
    }//GEN-LAST:event_btnAdicionarUserActionPerformed

    private void btnModificarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUserActionPerformed
        // índice do item selecionado
        int i = lstUsers.getSelectionModel().getMaxSelectionIndex();

        javax.swing.JPasswordField pfValidar = new javax.swing.JPasswordField();
        javax.swing.JTextField tfNome = new javax.swing.JTextField(users.get(i).getNome());
        javax.swing.JPasswordField pfSenha = new javax.swing.JPasswordField(users.get(i).getSenha());
        Object[] message = {
            "Senha: ", pfValidar,
        };
        pfValidar.setEchoChar('\u2022');
        
        int opt = JOptionPane.showConfirmDialog(null, message, "Insira a senha antiga:", JOptionPane.PLAIN_MESSAGE);
        
        if(opt == JOptionPane.OK_OPTION ) {
            if (pfValidar.getText().equals(users.get(i).getSenha())) {
                Object[] message2 = {
                    "Nome: ", tfNome,
                    "Senha: ", pfSenha,
                };
                pfSenha.setEchoChar('\u2022');

                int opt2 = JOptionPane.showConfirmDialog(null, message2, 
                        "Modificar perfil de usuário", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

                if(opt2 == JOptionPane.OK_OPTION) {
                    String newNome = tfNome.getText();
                    String newSenha = pfSenha.getText();

                    if (newNome.equals("") || newSenha.equals("")) {
                        JOptionPane.showMessageDialog(null, "Um ou mais campos não preenchidos.\nO perfil não foi adicionado!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
                    } else {
                        modUser.remove(i);
                        modUser.add(i, newNome);

                        users.get(i).modificar(newNome, newSenha, i);
                        users.get(i).setNome(newNome);
                        users.get(i).setSenha(newSenha);
                    }
                }
            } else {
            JOptionPane.showMessageDialog(null, "Senha inválida!",
                "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        } 
    }//GEN-LAST:event_btnModificarUserActionPerformed

    private void btnExcluirUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUserActionPerformed
        // Tirar da lista
        int dialogResult = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION){
            int index = lstUsers.getSelectionModel().getMaxSelectionIndex();
            modUser.remove(index);

            // Tirar do ArrayList
            User userRemove = users.get(index);
            users.remove(index);
            userRemove.apagarUser(index);   // apagar do arquivo
            
        }
    }//GEN-LAST:event_btnExcluirUserActionPerformed

    private void btnEntrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarUserActionPerformed
        javax.swing.JPasswordField pfSenha = new javax.swing.JPasswordField();
        int i = lstUsers.getSelectionModel().getMaxSelectionIndex();

        Object[] message = {
            "Senha: ", pfSenha,
        };
        pfSenha.setEchoChar('\u2022');
        int option = JOptionPane.showConfirmDialog(null, message, "Digite a senha para acessar:", JOptionPane.PLAIN_MESSAGE);

        if(option == JOptionPane.OK_OPTION) {
            if (pfSenha.getText().equals(users.get(i).getSenha())) {
                TelaDeck telaDeck = new TelaDeck(users.get(i));
                telaDeck.setVisible(true);
            } else { // Verificando se a senha colocada é a correta!
                JOptionPane.showMessageDialog(null, "Senha inválida!",
                    "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEntrarUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarUser;
    private javax.swing.JButton btnEntrarUser;
    private javax.swing.JButton btnExcluirUser;
    private javax.swing.JButton btnModificarUser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstUsers;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelUser;
    // End of variables declaration//GEN-END:variables
}
