/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import flashcards.Card;
import flashcards.Deck;
import flashcards.Estudo;
import java.awt.Color;



/**
 *
 * @author felip
 */
public class TelaEstudar extends javax.swing.JFrame {   
    private Deck deck;
    private Estudo estudo;
    private boolean cardFrente = true;    // para alternar entre verso e frente do card
    private javax.swing.Timer timer;
    
    private int idxAtual = 0;
    /**
     * Creates new form TelaEstudar
     */
    public TelaEstudar(Deck deck) {
        this.deck = deck;
        this.estudo = new Estudo(deck);
        initComponents();
        
        atualizaCard();
        mostraFrente();
        lblTitulo.setText("FRENTE");
        if (deck.getCards().size() == 1) {
            panelTras.setVisible(false);
        }
        
        java.awt.Point panelFrentePosition = panelFrente.getLocation();
        panelTras.setLocation(panelFrentePosition);
        panelTras.setSize(panelFrente.getSize());

        timer = new javax.swing.Timer(0,
            new java.awt.event.ActionListener(){  
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e){
                java.awt.Point p = panelFrente.getLocation();
                if (p.getX() > -294) {
                    p.setLocation(p.getX()-5, p.getY());
                    panelFrente.setLocation(p);
                    
                } else {
                    if (deck.getCards().size() - idxAtual == 1)
                        panelTras.setVisible(false);
                    else if (deck.getCards().size() - idxAtual == 0) {
                        dispose();
                    }
                    panelFrente.setLocation(panelFrentePosition);
                    timer.stop();
                }
            }
        });
    }
    
    
    // formatar texto do card. Caso ele seja muito grande, ir para nova linha
    // usando <html>, <body> e <br>. Tem que ser com a fonte específica selecionada
    private String formatarTexto(String s, int length) {
        String htmlInit = "<html><body>";
        String htmlFinal = "</html></body>";
        
        String txt = s;
        int limit = 29;
        if (length > limit) {
            StringBuilder txtHTML = new StringBuilder(htmlInit + s + htmlFinal);
            for (int i = limit + htmlInit.length(); i >= 0; i--) {
                if (txtHTML.charAt(i) == ' ') {
                    txt = txtHTML.insert(i+1, "<br>").toString();
                    txtHTML.delete(0, i+5).toString();
                    break;
                } else if (i == 0) {
                    txt = txtHTML.insert(htmlInit.length()+limit, "<br>").toString();
                    txtHTML.delete(0, htmlInit.length()+limit).toString();
                    break;
                }
            }
            txtHTML.delete(txtHTML.length() - htmlFinal.length(), txtHTML.length()).toString();
            formatarTexto(txtHTML.toString(), txtHTML.length());    // recursividade
        }
        return txt;
    }
    
    private Card atualizaCard() {
        Card proximo = estudo.proximoCard();
        return proximo;
    }
    
    private void mostraVerso() {
        Card c = estudo.getPrimeiroCard();
        if (c != null) {
            String txtVerso = c.getVerso();
            txtVerso = formatarTexto(txtVerso, txtVerso.length());
            lblCard2.setText(txtVerso);
        }
    }
    
    private void mostraFrente() {
        Card c = estudo.getPrimeiroCard();
        if (c != null) {
            String txtFrente = c.getFrente();
            txtFrente = formatarTexto(txtFrente, txtFrente.length());
            lblCard2.setText(txtFrente);
        }
    }
    
    // Mostra frente no cartão de trás
    private void mostraFrente2() {
        Card c = estudo.getPrimeiroCard();
        if (c != null) {
            String txtFrente = c.getFrente();
            txtFrente = formatarTexto(txtFrente, txtFrente.length());
            lblCard1.setText(txtFrente);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelFrente = new javax.swing.JPanel();
        lblCard2 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblVerso = new javax.swing.JLabel();
        panelTras = new javax.swing.JPanel();
        lblCard1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAcertei = new javax.swing.JButton();
        btnErrei = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));

        jLayeredPane1.setBackground(new java.awt.Color(245, 245, 245));

        panelFrente.setBackground(new java.awt.Color(255, 255, 255));
        panelFrente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));

        lblCard2.setBackground(new java.awt.Color(255, 255, 255));
        lblCard2.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        lblCard2.setAlignmentX(0.5F);
        lblCard2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCard2lblCard2MouseClicked(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setForeground(new java.awt.Color(156, 154, 154));
        lblTitulo.setAlignmentX(0.5F);

        lblVerso.setBackground(new java.awt.Color(255, 255, 255));
        lblVerso.setOpaque(true);

        javax.swing.GroupLayout panelFrenteLayout = new javax.swing.GroupLayout(panelFrente);
        panelFrente.setLayout(panelFrenteLayout);
        panelFrenteLayout.setHorizontalGroup(
            panelFrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFrenteLayout.createSequentialGroup()
                .addGroup(panelFrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFrenteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCard2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(lblVerso, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelFrenteLayout.setVerticalGroup(
            panelFrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFrenteLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblVerso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelTras.setBackground(new java.awt.Color(255, 255, 255));
        panelTras.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));

        lblCard1.setBackground(new java.awt.Color(255, 255, 255));
        lblCard1.setAlignmentX(0.5F);
        lblCard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelTrasLayout = new javax.swing.GroupLayout(panelTras);
        panelTras.setLayout(panelTrasLayout);
        panelTrasLayout.setHorizontalGroup(
            panelTrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCard1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTrasLayout.setVerticalGroup(
            panelTrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCard1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.setLayer(panelFrente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panelTras, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(panelFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(130, Short.MAX_VALUE)
                    .addComponent(panelTras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(161, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(panelFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(37, Short.MAX_VALUE)
                    .addComponent(panelTras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAcertei.setText("Acertei");
        btnAcertei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcerteiActionPerformed(evt);
            }
        });

        btnErrei.setText("Errei");
        btnErrei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErreiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnAcertei, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btnErrei, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcertei, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnErrei, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void animation() {
        // start timer to provide state change and repaint
        //Move every (approx) 5 milliseconds        

    }
    
    
    private void btnAcerteiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcerteiActionPerformed
        estudo.acertei();
        apertaBotao();
    }//GEN-LAST:event_btnAcerteiActionPerformed

    private void apertaBotao() {
        if(!timer.isRunning()) {
            timer.start();
        }
        else
            timer.stop();
        
        if (atualizaCard() != null) {
            mostraFrente();
            mostraFrente2();
        }
        idxAtual += 1;
    }
    
    private void btnErreiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErreiActionPerformed
        estudo.errei();
        apertaBotao();
    }//GEN-LAST:event_btnErreiActionPerformed

    private void lblCard2lblCard2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCard2lblCard2MouseClicked
        if (cardFrente) {
            cardFrente = false;
            mostraVerso();
            lblTitulo.setText("VERSO");
            lblVerso.setBackground(new java.awt.Color(121,179,255));
        }
        else {
            mostraFrente();
            cardFrente = true;
            lblTitulo.setText("FRENTE");
            lblVerso.setBackground(new java.awt.Color(255,255,255));
        }
    }//GEN-LAST:event_lblCard2lblCard2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstudar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstudar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstudar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstudar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstudar(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcertei;
    private javax.swing.JButton btnErrei;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCard1;
    private javax.swing.JLabel lblCard2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVerso;
    private javax.swing.JPanel panelFrente;
    private javax.swing.JPanel panelTras;
    // End of variables declaration//GEN-END:variables
}
