package frames;

import flashcards.Data;
import flashcards.Deck;
import flashcards.User;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Calendar;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felip
 */
public class TelaDeck extends javax.swing.JFrame {
    ArrayList<Deck> decks;
    private User user;
    private boolean tfClicked = false;
    private DefaultListModel mod = new DefaultListModel();
    
    /**
     * Creates new form Layout
     */
    public TelaDeck(User user) {
        this.user = user;
        
        decks = user.getDecks();
        
        initComponents();
        panelInicial.requestFocus();
        
        txtAdicionar.setForeground(java.awt.Color.GRAY);
        txtAdicionar.setText("Adicionar Deque");
        
        // habilitar ou desabilitar botões se um item estiver selecionado ou nao
        lstDeque.setFixedCellHeight(30);
        lstDeque.addListSelectionListener((ListSelectionEvent e) -> {
            if (lstDeque.getSelectedValue() != null) {
                // habilitar botões
                btnAcessar.setEnabled(true);
                btnRenomear.setEnabled(true);
                btnExcluir.setEnabled(true);
                lblVezesEstudadas.setEnabled(true);
                lblVezesEstudadasMostrar.setEnabled(true);
                lblData.setEnabled(true);
                lblMostraData.setEnabled(true);
                
                // mostrar data de criação
                int index = lstDeque.getSelectionModel().getMaxSelectionIndex();
                lblMostraData.setText(decks.get(index).getData().imprimirData());
                
                //Atualizar quantidade de vezes que o deck foi estudado:
                lblVezesEstudadasMostrar.setText(decks.get(index).getVezesEstudadas() + " vezes");
            } else {
                // desabilitar botões
                btnAcessar.setEnabled(false);
                btnRenomear.setEnabled(false);
                btnExcluir.setEnabled(false);
                lblVezesEstudadas.setEnabled(false);
                lblVezesEstudadasMostrar.setEnabled(false);
                lblData.setEnabled(false);
                lblMostraData.setEnabled(false);
            }
        });
        
        // Carregar decks adicionados anteriormente:
        if(user.isCarregouDados() == false) {
            int iterator = 0;
            boolean verificador;

            do {
                Deck deck = new Deck(user);
                verificador = deck.carregarDeck(iterator);
                if (verificador && deck.getNome() != null)
                    decks.add(deck);
                ++iterator;
            } while(verificador);
            
            user.setCarregouDados(true);
        }
        
        // Colocar os decks na tabela (Se foram adicionados anteriormente):
        lstDeque.setModel(mod);
        for(int i = 0; i < decks.size(); ++i) {
            mod.addElement(decks.get(i).getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicial = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        txtAdicionar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnAcessar = new javax.swing.JButton();
        btnRenomear = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstDeque = new javax.swing.JList<>();
        panelHistorico = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        lblMostraData = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblVezesEstudadas = new javax.swing.JLabel();
        lblVezesEstudadasMostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Decks");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelInicial.setBackground(new java.awt.Color(255, 255, 255));
        panelInicial.setRequestFocusEnabled(false);
        panelInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelInicialMouseClicked(evt);
            }
        });

        btnAdicionar.setBackground(new java.awt.Color(198, 247, 247));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        txtAdicionar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAdicionarMousePressed(evt);
            }
        });
        txtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdicionarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAcessar.setText("Acessar");
        btnAcessar.setEnabled(false);
        btnAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarActionPerformed(evt);
            }
        });

        btnRenomear.setText("Renomear");
        btnRenomear.setEnabled(false);
        btnRenomear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenomearActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Decks de '" + user.getNome() + "'"));
        jPanel5.setBackground(new java.awt.Color(245, 245, 245));

        lstDeque.setToolTipText("");
        jScrollPane4.setViewportView(lstDeque);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        panelHistorico.setBackground(new java.awt.Color(245, 245, 245));
        panelHistorico.setBorder(javax.swing.BorderFactory.createTitledBorder("Histórico"));
        panelHistorico.setPreferredSize(new java.awt.Dimension(158, 90));

        lblData.setText("Data de criação:");
        lblData.setEnabled(false);

        lblMostraData.setText("DD/MM/AAAA");
        lblMostraData.setEnabled(false);

        lblVezesEstudadas.setText("Quantidade de vezes estudadas:");
        lblVezesEstudadas.setEnabled(false);

        lblVezesEstudadasMostrar.setText("0");
        lblVezesEstudadasMostrar.setEnabled(false);

        javax.swing.GroupLayout panelHistoricoLayout = new javax.swing.GroupLayout(panelHistorico);
        panelHistorico.setLayout(panelHistoricoLayout);
        panelHistoricoLayout.setHorizontalGroup(
            panelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoricoLayout.createSequentialGroup()
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMostraData, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
            .addGroup(panelHistoricoLayout.createSequentialGroup()
                .addGroup(panelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVezesEstudadas)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVezesEstudadasMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHistoricoLayout.setVerticalGroup(
            panelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoricoLayout.createSequentialGroup()
                .addGroup(panelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(lblMostraData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblVezesEstudadas, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVezesEstudadasMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnRenomear)
                        .addGap(56, 56, 56)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRenomear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInicialLayout = new javax.swing.GroupLayout(panelInicial);
        panelInicial.setLayout(panelInicialLayout);
        panelInicialLayout.setHorizontalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelInicialLayout.setVerticalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        getContentPane().add(panelInicial, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInicialMouseClicked
        jPanelMouseClicked(panelInicial);
    }//GEN-LAST:event_panelInicialMouseClicked

    private void txtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdicionarActionPerformed
        btnAdicionar.doClick();
        panelInicial.requestFocus();
    }//GEN-LAST:event_txtAdicionarActionPerformed

    private void txtAdicionarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdicionarMousePressed
        if(!tfClicked){
            tfClicked=true;
            txtAdicionar.setText("");
            txtAdicionar.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtAdicionarMousePressed

    
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // adicionar deque na lista se o usuário digitou algo
        lstDeque.setModel(mod);
        if (!txtAdicionar.getText().equals("") && txtAdicionar.getForeground() != Color.GRAY) {
            String nomeDeck = txtAdicionar.getText().trim();
            
            // Adicionando data de criação:
            
            Calendar c = Calendar.getInstance();
            
            Data data = new Data(c.get(Calendar.DAY_OF_MONTH), c.get(Calendar.MONTH), c.get(Calendar.YEAR), c.get(Calendar.HOUR_OF_DAY));
            
            Deck newDeck = new Deck(nomeDeck, data);
            newDeck.setUser(user);
            newDeck.salvarDeck();
            decks.add(newDeck);
            
            
            mod.addElement(nomeDeck);
            
        } else {
            JOptionPane.showMessageDialog(null, "Campo não preenchido!",
                        "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
        // retornar com texto placeholder
        txtAdicionar.setForeground(java.awt.Color.GRAY);
        txtAdicionar.setText("Adicionar Deque");
        tfClicked = false;
   
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        jPanelMouseClicked(jPanel2);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void btnRenomearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenomearActionPerformed
        // indice do ultimo item selecionado
        int index = lstDeque.getSelectionModel().getMaxSelectionIndex();
        
        String text = JOptionPane.showInputDialog("Renomear deque", mod.getElementAt(index));
        
        if (text != null) {
            String newitem = text.trim();
            if (!newitem.isEmpty()) {
                mod.remove(index);
                mod.add(index, newitem);
                decks.get(index).atualizaArquivo(newitem, index, 1);
                decks.get(index).setNome(newitem);
                lstDeque.getSelectionModel().setLeadSelectionIndex(index);
            }
        }
    }//GEN-LAST:event_btnRenomearActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION){
            int index = lstDeque.getSelectionModel().getMaxSelectionIndex();
            mod.remove(index);
            decks.get(index).apagarDeck(index); // apagar do arquivo
            decks.remove(index);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarActionPerformed
        int index = lstDeque.getSelectionModel().getMaxSelectionIndex();
        TelaCard telaDeck = new TelaCard(decks.get(index));
        telaDeck.setVisible(true);
        decks.set(index, telaDeck.getDeck());
        decks.get(index).setIndiceDoDeckAtual(index);
    }//GEN-LAST:event_btnAcessarActionPerformed

    private void jPanelMouseClicked(javax.swing.JPanel jPanel) {
        jPanel.requestFocus();
        if (txtAdicionar.getText().isEmpty()) {
            txtAdicionar.setForeground(java.awt.Color.GRAY);
            txtAdicionar.setText("Adicionar Deque");
            tfClicked = false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeck(null).setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessar;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRenomear;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblMostraData;
    private javax.swing.JLabel lblVezesEstudadas;
    private javax.swing.JLabel lblVezesEstudadasMostrar;
    private javax.swing.JList<String> lstDeque;
    private javax.swing.JPanel panelHistorico;
    private javax.swing.JPanel panelInicial;
    private javax.swing.JTextField txtAdicionar;
    // End of variables declaration//GEN-END:variables
}
